name       : libdbi
version    : 0.9.0
release    : 1
source     :
    - http://internode.dl.sourceforge.net/project/libdbi/libdbi/libdbi-0.9.0/libdbi-0.9.0.tar.gz : dafb6cdca524c628df832b6dd0bf8fabceb103248edb21762c02d3068fca4503
license    : LGPL-2.1
summary    : libdbi implements a database-independent abstraction layer in C, similar to the DBI/DBD layer in Perl
description: |
    Writing one generic set of code, programmers can leverage the power of multiple databases and multiple simultaneous database connections by using this framework.
builddeps  :
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
